version: '3.8'

services:
  mock-broker-server:
    build: .
    container_name: mock-broker-server
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
    command: ['uvicorn', 'main:app', '--host', '0.0.0.0', '--port', '8000']
