version: '3.8'

services:
  trading_go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_go
    ports:
      - '8090:8090'
    volumes:
      - .:/app
    command: /tradehub
